version: "3"
services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
    container_name: express-app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=myapp
    # 기본적으로 docker-compose내의 컨테이너는 같은 네트워크 환경을 공유하지만, 명시적으로 써줌
    networks:
      - app-network

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp
    volumes:
      # 컨테이너 종료되어도 데이터 유지를 위한 volume 선언
      - db-data:/var/lib/mysql
      # 초기 테이블 셋업을 위해 선언
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

# db-data라는 volume 생성
volumes:
  db-data:
