version: "3"
services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
    container_name: express-app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=myapp
    networks:
      - app-network

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
